### ISSUE TITLE
There is no cb_IP.h

### ISSUE THREAD

**Issue by flipflop22** [u-blox/ublox-odin-w2-drivers-docs-mbed-5#2]
the mbed_wifi_ap_sequence.ping shows that it needs cb_IP.h. However I don't find this stack in mbed_os.

**Comment by asifrizwanubx** [comment]
This is an old document (most probably target for mbed 3). WiFi AP is not supported for ODIN-W2 in Mbed OS 5 at the moment. WiFi AP feature will be target in the future ODIN-W2 Mbed OS 5 releases.

**Comment by asifrizwanubx** [comment]
@flipflop22 Does this answer your question?

**Comment by flipflop22** [comment]
but it provides the C stack rite?

**Comment by asifrizwanubx** [comment]
Stack is provided in Pre-compiled binary module which includes u-blox Wi-Fi and Bluetooth drivers for Arm Mbed OS. And the recomended API is C++ via the OdinWiFiInterface class for WiFi. Bluetooth C++ API will be target in the future ODIN-W2 Mbed OS 5 releases.
